services:
  haproxy:
    image: haproxy:latest
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/certs/cert.pem:ro
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:3001:3001"
      # - "127.0.0.1:8080:80"
      # - "127.0.0.1:4443:443"
      # - "127.0.0.1:3001:3001"

  careers:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    mem_limit: 100m
    cpus: 0.1
    volumes:
      - ./database:/code/database
      - ./resume_files:/code/resume_files
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s

  adminer:
    image: adminer
    restart: always
    volumes:
      - "./database:/app:rw"
      - "./login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php"
    environment:
      - ADMINER_PLUGINS='login-password-less'
      - ADMINER_DESIGN='dracula'
    ports:
      - 3303:8080
