services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:3001:3001"

  careers:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 500m
    cpus: 0.5
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
