services:
  haproxy:
    image: haproxy:2.8.2-bullseye
    restart: always
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/certs/cert.pem:ro
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:3001:3001"
      # - "127.0.0.1:8080:80"
      # - "127.0.0.1:4443:443"
      # - "127.0.0.1:3001:3001"

  careers:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    mem_limit: 100m
    cpus: 0.1
    environment:
      - mysql_mode=True
      - mysql_hostname=mysql
      - mysql_database=careersdb
      - mysql_username=careers_dbuser
      - mysql_password=7O7dxwqV8e6aUCytIhk=
    volumes:
      - ./database:/code/database
      - ./resume_files:/code/app/resume_files
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s

  mysql:
    image: mysql:8.0.34-debian
    restart: always
    environment:
      MYSQL_DATABASE: careersdb
      MYSQL_USER: careers_dbuser
      MYSQL_PASSWORD: 7O7dxwqV8e6aUCytIhk=
      MYSQL_ROOT_PASSWORD: 7O7dxwqVqV8e6aUCytI=

  adminer:
    image: adminer:4.8.1-standalone
    depends_on:
      - mysql
    restart: always
    # ports:
    #   - 8080:8080
