apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-web-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.name }}-web-app
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}-web-app
    spec:
      containers:
      - name: {{ .Values.image.name }}-app-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "20m"
          limits:
            memory: "100Mi"
            cpu: "100m"
