apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-web-app-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: {{ .Values.image.name }}-web-app
